### ISSUE TITLE
Create a trigger word exemption list

### ISSUE THREAD

**Issue by shombando** [fade/harlie#2]
## Current state 
The bot uses a list of trigger words that can be seen via the `!trigger` command. This list is updated as trigger words are used so it keeps changing. Since there's not a timeout period for words that were recently on the list, the same word can (and has) replaced itself on the trigger list. 

## Desired state
The bot does not add words on the exemption list to the list of trigger words. These can be the most X common English words (suggest 100 including parts of speech like articles, etc.) or arbitrary set defined by author. This will prevent the bot from being unnecessarily noisy and trigger often in the middle of conversation.

## Stretch state
- The bot maintains a list of recently used trigger words (depth of list defined by author) in a FIFO fashion, that is also exempt from trigger list. So there's more variety in trigger scenarios.
- Community can add words to the exemption list. This might be ripe for abuse so maybe more of a mute a keyword for X amount of time might be a better implementation.

Please let me know if further clarification is helpful.

**Comment by shombando** [comment]
The trigger word minimum length change from 4 to 6 solved most of the concerns. Closing as resolved. Cheers!

**Comment by fade** [comment]
thanks. I think there is more potential for improvement around triggers. I may still add a list of verboten words that can be edited by users via an in-channel command.
